# -*- coding: utf-8 -*-
"""Tugas Sistem Persamaan Non Linear

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1TSFPjDsteCvTJBeOOP2AJeFMWYybzSAY
"""

"""
Penyelesaian Sistem Persamaan Non-Linear
NIM: 27
NIMx: 27 mod 4 = 3
Kombinasi: g1B dan g2B (Halaman 6)

Sistem Persamaan:
f1(x,y) = x² + xy - 10 = 0
f2(x,y) = y + 3xy² - 57 = 0

Fungsi Iterasi:
g1B: x = √(10 - xy)
g2B: y = √((57 - y)/(3x))
"""

import numpy as np
import pandas as pd
from tabulate import tabulate
import warnings
warnings.filterwarnings('ignore')

# ==================== DEFINISI FUNGSI ====================

def f1(x, y):
    """f1(x,y) = x² + xy - 10"""
    return x**2 + x*y - 10

def f2(x, y):
    """f2(x,y) = y + 3xy² - 57"""
    return y + 3*x*y**2 - 57

# Turunan parsial untuk Newton-Raphson
def df1_dx(x, y):
    """∂f1/∂x = 2x + y"""
    return 2*x + y

def df1_dy(x, y):
    """∂f1/∂y = x"""
    return x

def df2_dx(x, y):
    """∂f2/∂x = 3y²"""
    return 3*y**2

def df2_dy(x, y):
    """∂f2/∂y = 1 + 6xy"""
    return 1 + 6*x*y

# ==================== FUNGSI ITERASI ====================

# Halaman 5: g1A dan g2A
def g1A(x, y):
    """g1A: x = (10 - x²)/y"""
    if abs(y) < 1e-10:
        raise ValueError("Pembagi y mendekati nol")
    return (10 - x**2) / y

def g2A(x, y):
    """g2A: y = 57 - 3xy²"""
    return 57 - 3*x*y**2

# Halaman 6: g1B dan g2B (YANG BENAR UNTUK NIMx = 3)
def g1B(x, y):
    """g1B: x = √(10 - xy)"""
    value = 10 - x*y
    if value < 0:
        raise ValueError("Nilai dalam akar negatif")
    return np.sqrt(value)

def g2B(x, y):
    """g2B: y = √((57 - y)/(3x))"""
    denominator = 3 * x
    if abs(denominator) < 1e-10:
        raise ValueError("Pembagi x mendekati nol")
    value = (57 - y) / denominator
    if value < 0:
        raise ValueError("Nilai dalam akar negatif")
    return np.sqrt(value)

# ==================== METODE ITERASI ====================

def metode_jacobi(x0, y0, epsilon, g1_func, g2_func, func_name, max_iter=1000):
    """Metode Iterasi Titik Tetap - Jacobi"""
    print("\n" + "="*80)
    print(f"METODE 1: ITERASI TITIK TETAP - JACOBI ({func_name})")
    print("="*80)
    print(f"Tebakan awal: x0 = {x0}, y0 = {y0}")
    print(f"Toleransi: ε = {epsilon}\n")

    iterations = []
    x, y = x0, y0

    for i in range(max_iter):
        try:
            # Hitung nilai baru secara simultan (Jacobi)
            x_new = g1_func(x, y)
            y_new = g2_func(x, y)

            if not np.isfinite(x_new) or not np.isfinite(y_new):
                raise ValueError("Nilai tidak valid (inf/nan)")

            error = max(abs(x_new - x), abs(y_new - y))

            iterations.append({
                'Iterasi': i + 1,
                'x': x_new,
                'y': y_new,
                'f1(x,y)': f1(x_new, y_new),
                'f2(x,y)': f2(x_new, y_new),
                'Error': error
            })

            # Cek divergensi (nilai terlalu besar)
            if abs(x_new) > 1e6 or abs(y_new) > 1e6:
                print(f"✗ DIVERGEN pada iterasi ke-{i+1} (nilai terlalu besar)")
                print(f"   x = {x_new:.6f}, y = {y_new:.6f}\n")
                df = pd.DataFrame(iterations[:min(10, len(iterations))])
                print("Beberapa Iterasi Awal:")
                print(tabulate(df, headers='keys', tablefmt='grid', floatfmt='.6f', showindex=False))
                return False, iterations, None, None

            if error < epsilon:
                print(f"✓ KONVERGEN pada iterasi ke-{i+1}")
                print(f"Solusi: x = {x_new:.10f}, y = {y_new:.10f}\n")

                df = pd.DataFrame(iterations[-5:])
                print("5 Iterasi Terakhir:")
                print(tabulate(df, headers='keys', tablefmt='grid', floatfmt='.10f', showindex=False))
                return True, iterations, x_new, y_new

            x, y = x_new, y_new

        except Exception as e:
            print(f"✗ DIVERGEN atau ERROR pada iterasi ke-{i+1}: {str(e)}")
            if iterations:
                df = pd.DataFrame(iterations[:min(10, len(iterations))])
                print("\nBeberapa Iterasi Awal:")
                print(tabulate(df, headers='keys', tablefmt='grid', floatfmt='.6f', showindex=False))
            return False, iterations, None, None

    print(f"✗ Maksimum iterasi ({max_iter}) tercapai")
    return False, iterations, None, None


def metode_seidel(x0, y0, epsilon, g1_func, g2_func, func_name, max_iter=1000):
    """Metode Iterasi Titik Tetap - Gauss-Seidel"""
    print("\n" + "="*80)
    print(f"METODE 2: ITERASI TITIK TETAP - GAUSS-SEIDEL ({func_name})")
    print("="*80)
    print(f"Tebakan awal: x0 = {x0}, y0 = {y0}")
    print(f"Toleransi: ε = {epsilon}\n")

    iterations = []
    x, y = x0, y0

    for i in range(max_iter):
        try:
            # Hitung x baru, lalu gunakan x baru untuk hitung y (Seidel)
            x_new = g1_func(x, y)
            if not np.isfinite(x_new):
                raise ValueError("Nilai x tidak valid (inf/nan)")

            y_new = g2_func(x_new, y)  # Menggunakan x_new
            if not np.isfinite(y_new):
                raise ValueError("Nilai y tidak valid (inf/nan)")

            error = max(abs(x_new - x), abs(y_new - y))

            iterations.append({
                'Iterasi': i + 1,
                'x': x_new,
                'y': y_new,
                'f1(x,y)': f1(x_new, y_new),
                'f2(x,y)': f2(x_new, y_new),
                'Error': error
            })

            # Cek divergensi
            if abs(x_new) > 1e6 or abs(y_new) > 1e6:
                print(f"✗ DIVERGEN pada iterasi ke-{i+1} (nilai terlalu besar)")
                print(f"   x = {x_new:.6f}, y = {y_new:.6f}\n")
                df = pd.DataFrame(iterations[:min(10, len(iterations))])
                print("Beberapa Iterasi Awal:")
                print(tabulate(df, headers='keys', tablefmt='grid', floatfmt='.6f', showindex=False))
                return False, iterations, None, None

            if error < epsilon:
                print(f"✓ KONVERGEN pada iterasi ke-{i+1}")
                print(f"Solusi: x = {x_new:.10f}, y = {y_new:.10f}\n")

                df = pd.DataFrame(iterations[-5:])
                print("5 Iterasi Terakhir:")
                print(tabulate(df, headers='keys', tablefmt='grid', floatfmt='.10f', showindex=False))
                return True, iterations, x_new, y_new

            x, y = x_new, y_new

        except Exception as e:
            print(f"✗ DIVERGEN atau ERROR pada iterasi ke-{i+1}: {str(e)}")
            if iterations:
                df = pd.DataFrame(iterations[:min(10, len(iterations))])
                print("\nBeberapa Iterasi Awal:")
                print(tabulate(df, headers='keys', tablefmt='grid', floatfmt='.6f', showindex=False))
            return False, iterations, None, None

    print(f"✗ Maksimum iterasi ({max_iter}) tercapai")
    return False, iterations, None, None


def metode_newton_raphson(x0, y0, epsilon, max_iter=1000):
    """Metode Newton-Raphson"""
    print("\n" + "="*80)
    print("METODE 3: NEWTON-RAPHSON")
    print("="*80)
    print(f"Tebakan awal: x0 = {x0}, y0 = {y0}")
    print(f"Toleransi: ε = {epsilon}\n")

    iterations = []
    x, y = x0, y0

    for i in range(max_iter):
        # Hitung matriks Jacobian
        J11 = df1_dx(x, y)
        J12 = df1_dy(x, y)
        J21 = df2_dx(x, y)
        J22 = df2_dy(x, y)

        det = J11 * J22 - J12 * J21

        if abs(det) < 1e-10:
            print("✗ DIVERGEN: Jacobian singular")
            return False, iterations, None, None

        F1 = f1(x, y)
        F2 = f2(x, y)

        # Hitung delta menggunakan inverse Jacobian
        dx = (J22 * F1 - J12 * F2) / det
        dy = (J11 * F2 - J21 * F1) / det

        x_new = x - dx
        y_new = y - dy

        error = max(abs(dx), abs(dy))

        iterations.append({
            'Iterasi': i + 1,
            'x': x_new,
            'y': y_new,
            'f1(x,y)': f1(x_new, y_new),
            'f2(x,y)': f2(x_new, y_new),
            'Error': error
        })

        if error < epsilon:
            print(f"✓ KONVERGEN pada iterasi ke-{i+1}")
            print(f"Solusi: x = {x_new:.10f}, y = {y_new:.10f}\n")

            df = pd.DataFrame(iterations[-5:])
            print("5 Iterasi Terakhir:")
            print(tabulate(df, headers='keys', tablefmt='grid', floatfmt='.10f', showindex=False))
            return True, iterations, x_new, y_new

        x, y = x_new, y_new

    print(f"✗ Maksimum iterasi ({max_iter}) tercapai")
    return False, iterations, None, None


def metode_secant(x0, y0, epsilon, max_iter=1000):
    """Metode Secant"""
    print("\n" + "="*80)
    print("METODE 4: SECANT")
    print("="*80)
    print(f"Tebakan awal: x0 = {x0}, y0 = {y0}")
    print(f"Toleransi: ε = {epsilon}\n")

    iterations = []

    # Inisialisasi dua titik awal
    x_prev, y_prev = x0, y0
    x, y = x0 + 0.01, y0 + 0.01

    for i in range(max_iter):
        f1_curr = f1(x, y)
        f2_curr = f2(x, y)
        f1_prev = f1(x_prev, y_prev)
        f2_prev = f2(x_prev, y_prev)

        dx = x - x_prev
        dy = y - y_prev

        if abs(dx) < 1e-10 and abs(dy) < 1e-10:
            print("✗ DIVERGEN: Pembagi terlalu kecil")
            return False, iterations, None, None

        # Aproksimasi turunan
        df1_dx_approx = (f1_curr - f1_prev) / dx if abs(dx) > 1e-10 else 0
        df2_dy_approx = (f2_curr - f2_prev) / dy if abs(dy) > 1e-10 else 0

        if abs(df1_dx_approx) < 1e-10 or abs(df2_dy_approx) < 1e-10:
            print("✗ DIVERGEN: Turunan terlalu kecil")
            return False, iterations, None, None

        x_new = x - f1_curr / df1_dx_approx
        y_new = y - f2_curr / df2_dy_approx

        error = max(abs(x_new - x), abs(y_new - y))

        iterations.append({
            'Iterasi': i + 1,
            'x': x_new,
            'y': y_new,
            'f1(x,y)': f1(x_new, y_new),
            'f2(x,y)': f2(x_new, y_new),
            'Error': error
        })

        if error < epsilon:
            print(f"✓ KONVERGEN pada iterasi ke-{i+1}")
            print(f"Solusi: x = {x_new:.10f}, y = {y_new:.10f}\n")

            df = pd.DataFrame(iterations[-5:])
            print("5 Iterasi Terakhir:")
            print(tabulate(df, headers='keys', tablefmt='grid', floatfmt='.10f', showindex=False))
            return True, iterations, x_new, y_new

        x_prev, y_prev = x, y
        x, y = x_new, y_new

    print(f"✗ Maksimum iterasi ({max_iter}) tercapai")
    return False, iterations, None, None


# ==================== PROGRAM UTAMA ====================

def main():
    print("="*80)
    print("PENYELESAIAN SISTEM PERSAMAAN NON-LINEAR")
    print("="*80)
    print("NIM: 27")
    print("NIMx: 27 mod 4 = 3")
    print("Kombinasi Fungsi: g1B dan g2B (Halaman 6)")
    print("\nSistem Persamaan:")
    print("  f1(x,y) = x² + xy - 10 = 0")
    print("  f2(x,y) = y + 3xy² - 57 = 0")
    print("\nFungsi Iterasi (NIMx = 3):")
    print("  g1B: x = √(10 - xy)")
    print("  g2B: y = √((57 - y)/(3x))")
    print("="*80)

    # Parameter
    x0 = 1.5
    y0 = 3.5
    epsilon = 0.000001

    # Jalankan semua metode
    results = {}

    # 1. Jacobi dengan g1B dan g2B
    success, iters, x_sol, y_sol = metode_jacobi(x0, y0, epsilon, g1B, g2B, "g1B dan g2B")
    results['Jacobi (g1B+g2B)'] = {'success': success, 'iterations': len(iters) if iters else 0,
                                    'x': x_sol, 'y': y_sol}

    # 2. Gauss-Seidel dengan g1B dan g2B
    success, iters, x_sol, y_sol = metode_seidel(x0, y0, epsilon, g1B, g2B, "g1B dan g2B")
    results['Seidel (g1B+g2B)'] = {'success': success, 'iterations': len(iters) if iters else 0,
                                    'x': x_sol, 'y': y_sol}

    # 3. Newton-Raphson
    success, iters, x_sol, y_sol = metode_newton_raphson(x0, y0, epsilon)
    results['Newton-Raphson'] = {'success': success, 'iterations': len(iters) if iters else 0,
                                  'x': x_sol, 'y': y_sol}

    # 4. Secant
    success, iters, x_sol, y_sol = metode_secant(x0, y0, epsilon)
    results['Secant'] = {'success': success, 'iterations': len(iters) if iters else 0,
                         'x': x_sol, 'y': y_sol}

    # Ringkasan hasil
    print("\n" + "="*80)
    print("RINGKASAN HASIL")
    print("="*80)

    summary_data = []
    for method, result in results.items():
        if result['success']:
            summary_data.append({
                'Metode': method,
                'Status': '✓ Konvergen',
                'Iterasi': result['iterations'],
                'x': f"{result['x']:.10f}",
                'y': f"{result['y']:.10f}"
            })
        else:
            summary_data.append({
                'Metode': method,
                'Status': '✗ Divergen',
                'Iterasi': result['iterations'] if result['iterations'] > 0 else '-',
                'x': '-',
                'y': '-'
            })

    df_summary = pd.DataFrame(summary_data)
    print(tabulate(df_summary, headers='keys', tablefmt='grid', showindex=False))

    print("\n" + "="*80)
    print("KESIMPULAN")
    print("="*80)
    print("Dari keempat metode yang diimplementasikan dengan kombinasi g1B dan g2B:")
    print("1. Fungsi iterasi g1B = √(10-xy) dan g2B = √((57-y)/(3x)) dari halaman 6")
    print("2. Metode Iterasi Titik Tetap (Jacobi & Seidel) bergantung pada konvergensi")
    print("   fungsi iterasi yang dipilih")
    print("3. Metode Newton-Raphson umumnya paling cepat konvergen (konvergensi kuadratik)")
    print("4. Metode Secant tidak memerlukan turunan eksplisit tetapi butuh dua titik awal")
    print("5. Konvergensi sangat bergantung pada pemilihan fungsi iterasi dan tebakan awal")
    print("\nCatatan: Solusi eksak sistem ini adalah x = 2, y = 3")
    print("         (dapat diverifikasi: 2² + 2(3) - 10 = 0 ✓ dan 3 + 3(2)(3²) - 57 = 0 ✓)")
    print("="*80)

# Jalankan program
if __name__ == "__main__":
    main()